# Generated by Django 2.1.3 on 2019-08-06 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AriticeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='文章标题')),
                ('aritice_user', models.CharField(max_length=60, verbose_name='文章作者')),
                ('aritice_gjz', models.CharField(max_length=60, verbose_name='文章关键字')),
                ('img_url', models.CharField(max_length=100, verbose_name='文章封面图')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2019, 8, 6, 13, 59, 18, 66938), verbose_name='文章创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directtory_name', models.CharField(max_length=80, verbose_name='一级目录')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, verbose_name='用户名称')),
                ('password', models.CharField(max_length=80, verbose_name='用户密码')),
                ('user_token', models.CharField(max_length=80, verbose_name='用户凭证')),
                ('register_time', models.DateTimeField(default=datetime.datetime(2019, 8, 6, 13, 59, 18, 65977))),
            ],
        ),
    ]
