# Generated by Django 2.1.3 on 2019-07-29 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, verbose_name='用户名称')),
                ('password', models.CharField(max_length=80, verbose_name='用户密码')),
                ('user_token', models.CharField(max_length=80, verbose_name='用户凭证')),
                ('register_token', models.DateTimeField(default=datetime.datetime(2019, 7, 29, 10, 17, 10, 646302))),
            ],
        ),
    ]
