# Generated by Django 2.1.3 on 2019-07-29 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='register_token',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 18, 2, 36, 509922)),
        ),
    ]
