# Generated by Django 2.1.3 on 2019-08-06 14:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_content', models.TextField(verbose_name='话术内容')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2019, 8, 6, 14, 3, 11, 978195), verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='Directory_Secondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_name', models.CharField(max_length=100, verbose_name='二级目录')),
                ('directtore_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.DirectoryModel', verbose_name='一级目录关系')),
            ],
        ),
        migrations.AlterField(
            model_name='ariticemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 14, 3, 11, 976139), verbose_name='文章创建时间'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 14, 3, 11, 975139)),
        ),
        migrations.AddField(
            model_name='content_directory',
            name='directory_secondary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Directory_Secondary', verbose_name='二级目录关系'),
        ),
    ]
