# Generated by Django 2.1.3 on 2019-08-07 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190806_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='login_user_type',
            field=models.IntegerField(default=1, verbose_name='用户登陆类型'),
        ),
        migrations.AlterField(
            model_name='ariticemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 10, 50, 32, 232166), verbose_name='文章创建时间'),
        ),
        migrations.AlterField(
            model_name='content_directory',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 10, 50, 32, 234162), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 10, 50, 32, 232166)),
        ),
    ]
