# Generated by Django 2.1.3 on 2019-07-31 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190729_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='AriticeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='文章标题')),
                ('aritice_user', models.CharField(max_length=60, verbose_name='文章作者')),
                ('aritice_gjz', models.CharField(max_length=60, verbose_name='文章关键字')),
                ('img_url', models.CharField(max_length=100, verbose_name='文章封面图')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2019, 7, 31, 14, 45, 18, 42358), verbose_name='文章创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 14, 45, 18, 41358)),
        ),
    ]
