# Generated by Django 2.1.3 on 2019-08-02 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20190731_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directtory_name', models.CharField(max_length=80, verbose_name='一级目录')),
            ],
        ),
        migrations.AlterField(
            model_name='ariticemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 2, 16, 32, 27, 359911), verbose_name='文章创建时间'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 2, 16, 32, 27, 359911)),
        ),
    ]
