# Generated by Django 2.1.3 on 2019-08-07 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190807_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariticemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 14, 18, 40, 458283), verbose_name='文章创建时间'),
        ),
        migrations.AlterField(
            model_name='content_directory',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 14, 18, 40, 460277), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='setting_web',
            name='xitong_name',
            field=models.CharField(default='XXX恋爱话术', max_length=200, verbose_name='系统名称'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 14, 18, 40, 454295)),
        ),
    ]
