# Generated by Django 2.1.3 on 2019-08-03 02:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190802_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory_Secondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_name', models.CharField(max_length=100, verbose_name='二级目录')),
                ('directtore_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.DirectoryModel', verbose_name='一级目录关系')),
            ],
        ),
        migrations.AlterField(
            model_name='ariticemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 10, 49, 11, 500791), verbose_name='文章创建时间'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 10, 49, 11, 499794)),
        ),
    ]
