# Generated by Django 2.1.3 on 2019-08-10 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20190807_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting_web',
            name='huiyuan_jieshao',
            field=models.CharField(default='会员权限', max_length=500, verbose_name='会员介绍'),
        ),
        migrations.AddField(
            model_name='setting_web',
            name='lx_admin',
            field=models.CharField(default='添加客服: xxxx', max_length=500, verbose_name='联系客服'),
        ),
        migrations.AlterField(
            model_name='ariticemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 10, 14, 28, 43, 954708), verbose_name='文章创建时间'),
        ),
        migrations.AlterField(
            model_name='content_directory',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 10, 14, 28, 43, 955705), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 10, 14, 28, 43, 953764)),
        ),
    ]
