# Generated by Django 2.1.3 on 2019-08-05 07:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20190803_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_content', models.TextField(verbose_name='话术内容')),
                ('directory_secondary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Directory_Secondary', verbose_name='二级目录关系')),
            ],
        ),
        migrations.AlterField(
            model_name='ariticemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 15, 32, 12, 899316), verbose_name='文章创建时间'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 15, 32, 12, 899316)),
        ),
    ]
