# Generated by Django 2.1.3 on 2019-08-05 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20190805_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_directory',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 15, 33, 10, 990552), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='ariticemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 15, 33, 10, 990552), verbose_name='文章创建时间'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 15, 33, 10, 990552)),
        ),
    ]
